language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest
before_deploy: "zip release.zip * -r"
deploy:
  provider: releases
  api_key: "826469b6d7d4ca246909c5d3902bd22b99828dd5"
  file: "release.zip"
  skip_cleanup: true
  on:
    tags: true
