language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest
before_deploy:
  - chmod +x gitdeploy.sh
  - ./gitdeploy.sh
  - zip Python-$TRAVIS_PYTHON_VERSION-v$TRAVIS_BUILD_NUMBER.zip * -r
deploy:
  provider: releases
  api_key: $GITPERM
  file: "Python-$TRAVIS_PYTHON_VERSION-v$TRAVIS_BUILD_NUMBER.zip"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-v[0-9]/
