language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest
before_deploy:
  - git config --global user.email "thomasnicollet@yahoo.fr"
  - git config --global user.name "nwmqpa"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Build number $TRAVIS_BUILD_NUMBER"
  - git push -q https://github.com/nwmqpa/OVH --tags
  - zip release.zip * -r
deploy:
  provider: releases
  api_key: $GITPERM
  file: "release.zip"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-v[0-9]/
