# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1479062764167");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1479066364167");
user_pref("browser.search.countryCode", "DK");
user_pref("browser.search.region", "DK");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160921204512");
user_pref("browser.slowStartup.averageTime", 797);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20160921204512");
user_pref("browser.startup.homepage_override.mstone", "45.4.0");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1479149160116");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1479062821417");
user_pref("datareporting.policy.firstRunTime", "1479062760115");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.main", 11);
user_pref("datareporting.sessions.current.startTime", "1479063024955");
user_pref("datareporting.sessions.current.totalTime", 3);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.0", "{\"s\":1479062759785,\"a\":7,\"t\":86,\"c\":true,\"m\":12,\"fp\":1681,\"sr\":1638}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1479062851055,\"a\":1,\"t\":58,\"c\":true,\"m\":12,\"fp\":1106,\"sr\":1228}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1479062916377,\"a\":2,\"t\":8,\"c\":true,\"m\":12,\"fp\":713,\"sr\":1060}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1479062972287,\"a\":1,\"t\":5,\"c\":true,\"m\":11,\"fp\":715,\"sr\":1100}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1479062986033,\"a\":1,\"t\":2,\"c\":true,\"m\":11,\"fp\":-1,\"sr\":-1}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.4.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.4.0");
user_pref("extensions.lastPlatformVersion", "45.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1474526330000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.4.0\",\"st\":1474526330000}}}");
user_pref("gecko.buildID", "20160921204512");
user_pref("gecko.mstone", "45.4.0");
user_pref("media.gmp-manager.buildID", "20160921204512");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 51441);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1479063024);
user_pref("toolkit.telemetry.cachedClientID", "2c95651d-169d-4db3-9756-4b9cc6ccaaf5");
user_pref("toolkit.telemetry.previousBuildID", "20160921204512");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
